### ISSUE TITLE
Staging can't sync the large amount of users

### ISSUE THREAD

**Issue by Hazelfire** [getguesstimate/guesstimate-server#213]
I'm trying to fix the auth bug on production. However, I am lost as to what the problem is. This could be it, but I now doubt it.
There is not just one bug here, there are quite a number of bugs, that are all work together to make this a very difficult problem to resolve.

I'm putting a checklist here just so I can keep track of the bugs I've found, so I can keep my sanity:

- [x] Production doesn't log runtime errors. This one makes it very difficult to find why an error was caused, I think the log for the error can be found under `log/production.log`, but that can't be opened without restarting the production backend, and I'm not sure I want to do that. Turning on logging for runtime errors (not sure how to do yet) is the first thing I'd like to do.
- [ ] Syncing more than 1000 users results in an error on the backend. This makes it difficult to uncover the problem in staging, as staging needs to sync with the current users to respond to user requests, and currently returns 500 status on any user request because it can't sync with auth0.
- [ ] Frontend doesn't consider non-happy paths in authentication flow. If the authentication flow fails, an invalid state is left in local storage, causing the frontend to crash. Local Storage information should be treated with more care, like with a parser (as you would do in Elm).

I'm going to try and fix these errors in the order given here.

**Comment by Hazelfire** [comment]
I should have fixed problem 1 with the following commit: 65e33d7950bb6997cfec94306bd95a0963880ecd. Although I'm really not sure what it will look like in staging (as I think it has a custom logger?), so I'd like to have a go.

**Comment by Hazelfire** [comment]
Ok, yes, that did fix the first error. Now onto the second

**Comment by OAGr** [comment]
" Syncing more than 1000 users results in an error on the backend. " -> My impression from talking earlier was that it seemed like we were using an API call incorrectly (asking for all users, even though we should have asked for 1k). If this is the case, it seems easy enough to try fixing, and see if that fixes production. 

I imagine it would be clear if it actively breaks the backend, plus we can have tests around it. So pushing the (attempted) fix to prod, maybe a few times, doesn't seem too bad to me.

**Comment by Hazelfire** [comment]
There are a lot of things I don't yet understand about this application, but I'm putting this here for reference:

The point of the id token is to provide user information without needing to call the backend... however I can't seem to find any use of the id token? Nor can I find the frontend ever touching an object that looks like an id token... I feel like this is quite important, as it's possible to do things like verify that the user has a subscription plan by checking the signature on a JWT token....

**Comment by OAGr** [comment]
"I can't seem to find any use of the id token"
I would have assumed we use it to identify the current user or something. 

It's possible we don't formally use it in the app. However, it's still likely useful for debugging. (It would allow us to look up users on auth0)

**Comment by Hazelfire** [comment]
We have an access token, not an id token, although I'm really not too sure about this and am a bit confused by the whole thing

**Comment by Hazelfire** [comment]
This seems to be fixed
